import "@/components/app/globals.css";
import type { Metadata } from "next";
import { Outfit, Poppins } from "next/font/google";
import "@/components/app/globals.css";
import { Toaster } from "react-hot-toast";
import { RegisterInstructorProvider } from "./instructor/_components/registerInstructorContext";

const PoppinsFont = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const OutfitFont = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${PoppinsFont.variable} ${OutfitFont.variable} antialiased overflow-x-hidden`}
      >
        <RegisterInstructorProvider>{children}</RegisterInstructorProvider>
        <Toaster />
      </body>
    </html>
  );
}
