import type { Metadata } from "next";
import { Poppins, Outfit } from "next/font/google";
// import "/globals.css";
import "../globals.css";
import { Toaster } from "react-hot-toast";
import { Sidebar } from "./components/side-bar";
import { ThemeProvider } from "@/components/theme-provider";

const PoppinsFont = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const OutfitFont = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${PoppinsFont.variable} ${OutfitFont.variable} antialiased flex h-screen w-screen overflow-hidden`}
      >
        <ThemeProvider defaultTheme="dark" storageKey="theme">
          <Sidebar />
          <main className="flex-1 overflow-y-auto h-full">{children}</main>
        </ThemeProvider>
        <Toaster />
      </body>
    </html>
  );
}
